package mx.unam.fciencias.myp.chat.models;

/**
 * Chat interface.
 *
 * @author Luis Daniel Aragon Bermudez 416041271
 */
public interface Chat {
    /**
     * Register a user. A user that has been registered is considered online until it has been unregistered. A user
     * that's online will receive chat updates.
     *
     * @param user The user that's been registered.
     */
    void register(AbstractChatUser user);

    /**
     * Unregister a user.
     *
     * @param user The user that's been unregistered.
     */
    void unregister(AbstractChatUser user);

    /**
     * Passes a notification to all online users. Implementations should consider what happens if the notification was
     * generated by an offline user.
     *
     * @param notification the notification.
     */
    void updateUsers(ChatNotification notification);

    /**
     * Retrieves a user's online status.
     *
     * @param user a user.
     * @return true if the user is online, false otherwise.
     */
    boolean isOnline(AbstractChatUser user);
}
